name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      - uses: ./
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'hello_world2'
          deta-project: 'default' 
          deta-project-dir: '.'
